const fs = require('fs');
const path = require('path');

// 주요 누락된 한자들의 실제 정보
const characterInfoMap = {
  諫: {
    pronunciation: '간',
    meaning: '간하다',
    strokeCount: 16,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  葛: {
    pronunciation: '갈',
    meaning: '칡',
    strokeCount: 12,
    radical: '艸',
    radicalName: '艸부',
    radicalStrokes: 6,
  },
  藤: {
    pronunciation: '등',
    meaning: '등나무',
    strokeCount: 18,
    radical: '艸',
    radicalName: '艸부',
    radicalStrokes: 6,
  },
  凱: {
    pronunciation: '개',
    meaning: '이길',
    strokeCount: 12,
    radical: '几',
    radicalName: '几부',
    radicalStrokes: 2,
  },
  坑: {
    pronunciation: '갱',
    meaning: '구덩이',
    strokeCount: 7,
    radical: '土',
    radicalName: '土부',
    radicalStrokes: 3,
  },
  揭: {
    pronunciation: '게',
    meaning: '들다',
    strokeCount: 12,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  晶: {
    pronunciation: '정',
    meaning: '맑을',
    strokeCount: 12,
    radical: '日',
    radicalName: '日부',
    radicalStrokes: 4,
  },
  乏: {
    pronunciation: '핍',
    meaning: '모자랄',
    strokeCount: 5,
    radical: '丿',
    radicalName: '丿부',
    radicalStrokes: 1,
  },
  遜: {
    pronunciation: '손',
    meaning: '겸손할',
    strokeCount: 14,
    radical: '辵',
    radicalName: '辵부',
    radicalStrokes: 7,
  },
  悶: {
    pronunciation: '민',
    meaning: '답답할',
    strokeCount: 12,
    radical: '心',
    radicalName: '心부',
    radicalStrokes: 4,
  },
  雇: {
    pronunciation: '고',
    meaning: '고용할',
    strokeCount: 12,
    radical: '隹',
    radicalName: '隹부',
    radicalStrokes: 8,
  },
  傭: {
    pronunciation: '용',
    meaning: '품팔이',
    strokeCount: 13,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  慌: {
    pronunciation: '황',
    meaning: '황급할',
    strokeCount: 12,
    radical: '心',
    radicalName: '心부',
    radicalStrokes: 4,
  },
  瓜: {
    pronunciation: '과',
    meaning: '오이',
    strokeCount: 5,
    radical: '瓜',
    radicalName: '瓜부',
    radicalStrokes: 5,
  },
  傀: {
    pronunciation: '괴',
    meaning: '괴뢰',
    strokeCount: 12,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  儡: {
    pronunciation: '뢰',
    meaning: '괴뢰',
    strokeCount: 17,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  絞: {
    pronunciation: '교',
    meaning: '꼬다',
    strokeCount: 12,
    radical: '糸',
    radicalName: '糸부',
    radicalStrokes: 6,
  },
  膠: {
    pronunciation: '교',
    meaning: '아교',
    strokeCount: 15,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  鞭: {
    pronunciation: '편',
    meaning: '채찍',
    strokeCount: 18,
    radical: '革',
    radicalName: '革부',
    radicalStrokes: 9,
  },
  狡: {
    pronunciation: '교',
    meaning: '교활할',
    strokeCount: 9,
    radical: '犬',
    radicalName: '犬부',
    radicalStrokes: 4,
  },
  猾: {
    pronunciation: '활',
    meaning: '교활할',
    strokeCount: 12,
    radical: '犬',
    radicalName: '犬부',
    radicalStrokes: 4,
  },
  闕: {
    pronunciation: '궐',
    meaning: '빠질',
    strokeCount: 18,
    radical: '門',
    radicalName: '門부',
    radicalStrokes: 8,
  },
  倦: {
    pronunciation: '권',
    meaning: '권태로울',
    strokeCount: 10,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  閨: {
    pronunciation: '규',
    meaning: '안방',
    strokeCount: 14,
    radical: '門',
    radicalName: '門부',
    radicalStrokes: 8,
  },
  繡: {
    pronunciation: '수',
    meaning: '수놓다',
    strokeCount: 18,
    radical: '糸',
    radicalName: '糸부',
    radicalStrokes: 6,
  },
  瑟: {
    pronunciation: '슬',
    meaning: '거문고',
    strokeCount: 13,
    radical: '玉',
    radicalName: '玉부',
    radicalStrokes: 5,
  },
  金: {
    pronunciation: '금',
    meaning: '쇠',
    strokeCount: 8,
    radical: '金',
    radicalName: '金부',
    radicalStrokes: 8,
  },
  融: {
    pronunciation: '융',
    meaning: '녹을',
    strokeCount: 16,
    radical: '虫',
    radicalName: '虫부',
    radicalStrokes: 6,
  },
  矜: {
    pronunciation: '긍',
    meaning: '긍지',
    strokeCount: 9,
    radical: '矛',
    radicalName: '矛부',
    radicalStrokes: 5,
  },
  禱: {
    pronunciation: '도',
    meaning: '기도',
    strokeCount: 18,
    radical: '示',
    radicalName: '示부',
    radicalStrokes: 5,
  },
  岐: {
    pronunciation: '기',
    meaning: '갈림길',
    strokeCount: 7,
    radical: '山',
    radicalName: '山부',
    radicalStrokes: 3,
  },
  瞞: {
    pronunciation: '만',
    meaning: '속일',
    strokeCount: 16,
    radical: '目',
    radicalName: '目부',
    radicalStrokes: 5,
  },
  憚: {
    pronunciation: '탄',
    meaning: '꺼릴',
    strokeCount: 15,
    radical: '心',
    radicalName: '心부',
    radicalStrokes: 4,
  },
  嗜: {
    pronunciation: '기',
    meaning: '즐길',
    strokeCount: 13,
    radical: '口',
    radicalName: '口부',
    radicalStrokes: 3,
  },
  懶: {
    pronunciation: '란',
    meaning: '게으를',
    strokeCount: 19,
    radical: '心',
    radicalName: '心부',
    radicalStrokes: 4,
  },
  拉: {
    pronunciation: '랍',
    meaning: '당길',
    strokeCount: 8,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  隸: {
    pronunciation: '예',
    meaning: '종',
    strokeCount: 17,
    radical: '隶',
    radicalName: '隶부',
    radicalStrokes: 8,
  },
  俸: {
    pronunciation: '봉',
    meaning: '봉급',
    strokeCount: 10,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  濃: {
    pronunciation: '농',
    meaning: '진할',
    strokeCount: 16,
    radical: '水',
    radicalName: '水부',
    radicalStrokes: 4,
  },
  陋: {
    pronunciation: '루',
    meaning: '비루할',
    strokeCount: 9,
    radical: '阜',
    radicalName: '阜부',
    radicalStrokes: 3,
  },
  腺: {
    pronunciation: '선',
    meaning: '샘',
    strokeCount: 13,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  鍛: {
    pronunciation: '단',
    meaning: '단련',
    strokeCount: 17,
    radical: '金',
    radicalName: '金부',
    radicalStrokes: 8,
  },
  膽: {
    pronunciation: '담',
    meaning: '쓸개',
    strokeCount: 17,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  囊: {
    pronunciation: '낭',
    meaning: '주머니',
    strokeCount: 22,
    radical: '口',
    radicalName: '口부',
    radicalStrokes: 3,
  },
  垈: {
    pronunciation: '대',
    meaning: '터',
    strokeCount: 8,
    radical: '土',
    radicalName: '土부',
    radicalStrokes: 3,
  },
  褙: {
    pronunciation: '배',
    meaning: '배자',
    strokeCount: 14,
    radical: '衣',
    radicalName: '衣부',
    radicalStrokes: 6,
  },
  頓: {
    pronunciation: '돈',
    meaning: '머리숙일',
    strokeCount: 13,
    radical: '頁',
    radicalName: '頁부',
    radicalStrokes: 9,
  },
  窟: {
    pronunciation: '굴',
    meaning: '굴',
    strokeCount: 13,
    radical: '穴',
    radicalName: '穴부',
    radicalStrokes: 5,
  },
  棟: {
    pronunciation: '동',
    meaning: '마룻대',
    strokeCount: 12,
    radical: '木',
    radicalName: '木부',
    radicalStrokes: 4,
  },
  摩: {
    pronunciation: '마',
    meaning: '문지를',
    strokeCount: 15,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  擦: {
    pronunciation: '찰',
    meaning: '문지를',
    strokeCount: 17,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  萌: {
    pronunciation: '맹',
    meaning: '싹틀',
    strokeCount: 11,
    radical: '艸',
    radicalName: '艸부',
    radicalStrokes: 6,
  },
  蔑: {
    pronunciation: '멸',
    meaning: '업신여길',
    strokeCount: 14,
    radical: '艸',
    radicalName: '艸부',
    radicalStrokes: 6,
  },
  矛: {
    pronunciation: '모',
    meaning: '창',
    strokeCount: 5,
    radical: '矛',
    radicalName: '矛부',
    radicalStrokes: 5,
  },
  盾: {
    pronunciation: '순',
    meaning: '방패',
    strokeCount: 9,
    radical: '目',
    radicalName: '目부',
    radicalStrokes: 5,
  },
  茅: {
    pronunciation: '모',
    meaning: '띠',
    strokeCount: 8,
    radical: '艸',
    radicalName: '艸부',
    radicalStrokes: 6,
  },
  沐: {
    pronunciation: '목',
    meaning: '머리감을',
    strokeCount: 7,
    radical: '水',
    radicalName: '水부',
    radicalStrokes: 4,
  },
  昧: {
    pronunciation: '매',
    meaning: '어두울',
    strokeCount: 9,
    radical: '日',
    radicalName: '日부',
    radicalStrokes: 4,
  },
  描: {
    pronunciation: '묘',
    meaning: '그릴',
    strokeCount: 12,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  踊: {
    pronunciation: '용',
    meaning: '춤출',
    strokeCount: 14,
    radical: '足',
    radicalName: '足부',
    radicalStrokes: 7,
  },
  譚: {
    pronunciation: '담',
    meaning: '이야기',
    strokeCount: 19,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  侶: {
    pronunciation: '려',
    meaning: '짝',
    strokeCount: 9,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  掘: {
    pronunciation: '굴',
    meaning: '팔',
    strokeCount: 11,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  萃: {
    pronunciation: '췌',
    meaning: '모일',
    strokeCount: 11,
    radical: '艸',
    radicalName: '艸부',
    radicalStrokes: 6,
  },
  禦: {
    pronunciation: '어',
    meaning: '막을',
    strokeCount: 17,
    radical: '示',
    radicalName: '示부',
    radicalStrokes: 5,
  },
  賠: {
    pronunciation: '배',
    meaning: '배상',
    strokeCount: 15,
    radical: '貝',
    radicalName: '貝부',
    radicalStrokes: 7,
  },
  俳: {
    pronunciation: '배',
    meaning: '배우',
    strokeCount: 10,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  潭: {
    pronunciation: '담',
    meaning: '못',
    strokeCount: 15,
    radical: '水',
    radicalName: '水부',
    radicalStrokes: 4,
  },
  氾: {
    pronunciation: '범',
    meaning: '넓을',
    strokeCount: 5,
    radical: '水',
    radicalName: '水부',
    radicalStrokes: 4,
  },
  僻: {
    pronunciation: '벽',
    meaning: '외딴',
    strokeCount: 15,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  輔: {
    pronunciation: '보',
    meaning: '도울',
    strokeCount: 14,
    radical: '車',
    radicalName: '車부',
    radicalStrokes: 7,
  },
  祉: {
    pronunciation: '지',
    meaning: '복',
    strokeCount: 8,
    radical: '示',
    radicalName: '示부',
    radicalStrokes: 5,
  },
  訃: {
    pronunciation: '부',
    meaning: '부고',
    strokeCount: 9,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  娩: {
    pronunciation: '만',
    meaning: '해산',
    strokeCount: 10,
    radical: '女',
    radicalName: '女부',
    radicalStrokes: 3,
  },
  腔: {
    pronunciation: '강',
    meaning: '빈속',
    strokeCount: 12,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  誹: {
    pronunciation: '비',
    meaning: '비방',
    strokeCount: 15,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  謗: {
    pronunciation: '방',
    meaning: '비방',
    strokeCount: 17,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  喩: {
    pronunciation: '유',
    meaning: '비유',
    strokeCount: 12,
    radical: '口',
    radicalName: '口부',
    radicalStrokes: 3,
  },
  率: {
    pronunciation: '솔',
    meaning: '솔선',
    strokeCount: 11,
    radical: '玄',
    radicalName: '玄부',
    radicalStrokes: 5,
  },
  祠: {
    pronunciation: '사',
    meaning: '사당',
    strokeCount: 9,
    radical: '示',
    radicalName: '示부',
    radicalStrokes: 5,
  },
  赦: {
    pronunciation: '사',
    meaning: '사면',
    strokeCount: 11,
    radical: '赤',
    radicalName: '赤부',
    radicalStrokes: 7,
  },
  肢: {
    pronunciation: '지',
    meaning: '사지',
    strokeCount: 8,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  刹: {
    pronunciation: '찰',
    meaning: '절',
    strokeCount: 8,
    radical: '刀',
    radicalName: '刀부',
    radicalStrokes: 2,
  },
  奢: {
    pronunciation: '사',
    meaning: '사치',
    strokeCount: 12,
    radical: '大',
    radicalName: '大부',
    radicalStrokes: 3,
  },
  侈: {
    pronunciation: '치',
    meaning: '사치',
    strokeCount: 8,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  撒: {
    pronunciation: '살',
    meaning: '뿌릴',
    strokeCount: 15,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  揷: {
    pronunciation: '삽',
    meaning: '꽂을',
    strokeCount: 12,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  畵: {
    pronunciation: '화',
    meaning: '그림',
    strokeCount: 12,
    radical: '田',
    radicalName: '田부',
    radicalStrokes: 5,
  },
  圈: {
    pronunciation: '권',
    meaning: '둘레',
    strokeCount: 11,
    radical: '囗',
    radicalName: '囗부',
    radicalStrokes: 3,
  },
  殖: {
    pronunciation: '식',
    meaning: '번식',
    strokeCount: 12,
    radical: '歹',
    radicalName: '歹부',
    radicalStrokes: 4,
  },
  札: {
    pronunciation: '찰',
    meaning: '쪽지',
    strokeCount: 5,
    radical: '木',
    radicalName: '木부',
    radicalStrokes: 4,
  },
  翰: {
    pronunciation: '한',
    meaning: '붓',
    strokeCount: 16,
    radical: '羽',
    radicalName: '羽부',
    radicalStrokes: 6,
  },
  舶: {
    pronunciation: '박',
    meaning: '배',
    strokeCount: 11,
    radical: '舟',
    radicalName: '舟부',
    radicalStrokes: 6,
  },
  纖: {
    pronunciation: '섬',
    meaning: '가늘',
    strokeCount: 23,
    radical: '糸',
    radicalName: '糸부',
    radicalStrokes: 6,
  },
  紹: {
    pronunciation: '소',
    meaning: '이을',
    strokeCount: 11,
    radical: '糸',
    radicalName: '糸부',
    radicalStrokes: 6,
  },
  疎: {
    pronunciation: '소',
    meaning: '소원할',
    strokeCount: 12,
    radical: '疋',
    radicalName: '疋부',
    radicalStrokes: 5,
  },
  簾: {
    pronunciation: '렴',
    meaning: '발',
    strokeCount: 19,
    radical: '竹',
    radicalName: '竹부',
    radicalStrokes: 6,
  },
  斂: {
    pronunciation: '렴',
    meaning: '거둘',
    strokeCount: 17,
    radical: '攴',
    radicalName: '攴부',
    radicalStrokes: 4,
  },
  狩: {
    pronunciation: '수',
    meaning: '사냥',
    strokeCount: 9,
    radical: '犬',
    radicalName: '犬부',
    radicalStrokes: 4,
  },
  賂: {
    pronunciation: '뢰',
    meaning: '뇌물',
    strokeCount: 13,
    radical: '貝',
    radicalName: '貝부',
    radicalStrokes: 7,
  },
  羞: {
    pronunciation: '수',
    meaning: '부끄러울',
    strokeCount: 11,
    radical: '羊',
    radicalName: '羊부',
    radicalStrokes: 6,
  },
  粹: {
    pronunciation: '수',
    meaning: '순수할',
    strokeCount: 14,
    radical: '米',
    radicalName: '米부',
    radicalStrokes: 6,
  },
  託: {
    pronunciation: '탁',
    meaning: '부탁',
    strokeCount: 10,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  魔: {
    pronunciation: '마',
    meaning: '마귀',
    strokeCount: 20,
    radical: '鬼',
    radicalName: '鬼부',
    radicalStrokes: 10,
  },
  悼: {
    pronunciation: '도',
    meaning: '슬퍼할',
    strokeCount: 11,
    radical: '心',
    radicalName: '心부',
    radicalStrokes: 4,
  },
  齡: {
    pronunciation: '령',
    meaning: '나이',
    strokeCount: 20,
    radical: '齒',
    radicalName: '齒부',
    radicalStrokes: 15,
  },
  酸: {
    pronunciation: '산',
    meaning: '시다',
    strokeCount: 14,
    radical: '酉',
    radicalName: '酉부',
    radicalStrokes: 7,
  },
  厭: {
    pronunciation: '염',
    meaning: '싫어할',
    strokeCount: 14,
    radical: '厂',
    radicalName: '厂부',
    radicalStrokes: 2,
  },
  孃: {
    pronunciation: '낭',
    meaning: '아가씨',
    strokeCount: 20,
    radical: '女',
    radicalName: '女부',
    radicalStrokes: 3,
  },
  預: {
    pronunciation: '예',
    meaning: '미리',
    strokeCount: 13,
    radical: '頁',
    radicalName: '頁부',
    radicalStrokes: 9,
  },
  謬: {
    pronunciation: '류',
    meaning: '그릇될',
    strokeCount: 18,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  沃: {
    pronunciation: '옥',
    meaning: '기름질',
    strokeCount: 7,
    radical: '水',
    radicalName: '水부',
    radicalStrokes: 4,
  },
  歪: {
    pronunciation: '왜',
    meaning: '비뚤어질',
    strokeCount: 9,
    radical: '止',
    radicalName: '止부',
    radicalStrokes: 4,
  },
  倭: {
    pronunciation: '왜',
    meaning: '왜국',
    strokeCount: 10,
    radical: '人',
    radicalName: '人부',
    radicalStrokes: 2,
  },
  尿: {
    pronunciation: '뇨',
    meaning: '오줌',
    strokeCount: 7,
    radical: '尸',
    radicalName: '尸부',
    radicalStrokes: 3,
  },
  籃: {
    pronunciation: '남',
    meaning: '바구니',
    strokeCount: 20,
    radical: '竹',
    radicalName: '竹부',
    radicalStrokes: 6,
  },
  塞: {
    pronunciation: '새',
    meaning: '막을',
    strokeCount: 13,
    radical: '土',
    radicalName: '土부',
    radicalStrokes: 3,
  },
  夭: {
    pronunciation: '요',
    meaning: '일찍죽을',
    strokeCount: 4,
    radical: '大',
    radicalName: '大부',
    radicalStrokes: 3,
  },
  溶: {
    pronunciation: '용',
    meaning: '녹을',
    strokeCount: 13,
    radical: '水',
    radicalName: '水부',
    radicalStrokes: 4,
  },
  寓: {
    pronunciation: '우',
    meaning: '살',
    strokeCount: 12,
    radical: '宀',
    radicalName: '宀부',
    radicalStrokes: 3,
  },
  搬: {
    pronunciation: '반',
    meaning: '옮길',
    strokeCount: 13,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  鬱: {
    pronunciation: '울',
    meaning: '울적할',
    strokeCount: 29,
    radical: '鬯',
    radicalName: '鬯부',
    radicalStrokes: 10,
  },
  蝕: {
    pronunciation: '식',
    meaning: '갉아먹을',
    strokeCount: 14,
    radical: '虫',
    radicalName: '虫부',
    radicalStrokes: 6,
  },
  紐: {
    pronunciation: '뉴',
    meaning: '끈',
    strokeCount: 10,
    radical: '糸',
    radicalName: '糸부',
    radicalStrokes: 6,
  },
  匿: {
    pronunciation: '닉',
    meaning: '숨을',
    strokeCount: 10,
    radical: '匸',
    radicalName: '匸부',
    radicalStrokes: 2,
  },
  翌: {
    pronunciation: '익',
    meaning: '다음날',
    strokeCount: 11,
    radical: '羽',
    radicalName: '羽부',
    radicalStrokes: 6,
  },
  咽: {
    pronunciation: '인',
    meaning: '목구멍',
    strokeCount: 9,
    radical: '口',
    radicalName: '口부',
    radicalStrokes: 3,
  },
  喉: {
    pronunciation: '후',
    meaning: '목구멍',
    strokeCount: 12,
    radical: '口',
    radicalName: '口부',
    radicalStrokes: 3,
  },
  姙: {
    pronunciation: '임',
    meaning: '임신',
    strokeCount: 9,
    radical: '女',
    radicalName: '女부',
    radicalStrokes: 3,
  },
  娠: {
    pronunciation: '신',
    meaning: '임신',
    strokeCount: 10,
    radical: '女',
    radicalName: '女부',
    radicalStrokes: 3,
  },
  粒: {
    pronunciation: '립',
    meaning: '알',
    strokeCount: 11,
    radical: '米',
    radicalName: '米부',
    radicalStrokes: 6,
  },
  磁: {
    pronunciation: '자',
    meaning: '자석',
    strokeCount: 14,
    radical: '石',
    radicalName: '石부',
    radicalStrokes: 5,
  },
  諮: {
    pronunciation: '자',
    meaning: '물을',
    strokeCount: 16,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  碍: {
    pronunciation: '애',
    meaning: '방해',
    strokeCount: 13,
    radical: '石',
    radicalName: '石부',
    radicalStrokes: 5,
  },
  匠: {
    pronunciation: '장',
    meaning: '장인',
    strokeCount: 6,
    radical: '匚',
    radicalName: '匚부',
    radicalStrokes: 2,
  },
  顚: {
    pronunciation: '전',
    meaning: '넘어질',
    strokeCount: 19,
    radical: '頁',
    radicalName: '頁부',
    radicalStrokes: 9,
  },
  鋪: {
    pronunciation: '포',
    meaning: '포장',
    strokeCount: 15,
    radical: '金',
    radicalName: '金부',
    radicalStrokes: 8,
  },
  彫: {
    pronunciation: '조',
    meaning: '새길',
    strokeCount: 11,
    radical: '彡',
    radicalName: '彡부',
    radicalStrokes: 3,
  },
  劑: {
    pronunciation: '제',
    meaning: '약',
    strokeCount: 16,
    radical: '刀',
    radicalName: '刀부',
    radicalStrokes: 2,
  },
  閥: {
    pronunciation: '벌',
    meaning: '문벌',
    strokeCount: 14,
    radical: '門',
    radicalName: '門부',
    radicalStrokes: 8,
  },
  軸: {
    pronunciation: '축',
    meaning: '축',
    strokeCount: 12,
    radical: '車',
    radicalName: '車부',
    radicalStrokes: 7,
  },
  脂: {
    pronunciation: '지',
    meaning: '기름',
    strokeCount: 10,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  肪: {
    pronunciation: '방',
    meaning: '기름',
    strokeCount: 8,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  診: {
    pronunciation: '진',
    meaning: '진찰',
    strokeCount: 12,
    radical: '言',
    radicalName: '言부',
    radicalStrokes: 7,
  },
  療: {
    pronunciation: '료',
    meaning: '치료',
    strokeCount: 17,
    radical: '疒',
    radicalName: '疒부',
    radicalStrokes: 5,
  },
  塵: {
    pronunciation: '진',
    meaning: '먼지',
    strokeCount: 14,
    radical: '土',
    radicalName: '土부',
    radicalStrokes: 3,
  },
  窒: {
    pronunciation: '질',
    meaning: '막힐',
    strokeCount: 11,
    radical: '穴',
    radicalName: '穴부',
    radicalStrokes: 5,
  },
  燦: {
    pronunciation: '찬',
    meaning: '빛날',
    strokeCount: 17,
    radical: '火',
    radicalName: '火부',
    radicalStrokes: 4,
  },
  爛: {
    pronunciation: '란',
    meaning: '썩을',
    strokeCount: 21,
    radical: '火',
    radicalName: '火부',
    radicalStrokes: 4,
  },
  滄: {
    pronunciation: '창',
    meaning: '푸를',
    strokeCount: 13,
    radical: '水',
    radicalName: '水부',
    radicalStrokes: 4,
  },
  捷: {
    pronunciation: '첩',
    meaning: '빠를',
    strokeCount: 11,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  締: {
    pronunciation: '체',
    meaning: '맺을',
    strokeCount: 15,
    radical: '糸',
    radicalName: '糸부',
    radicalStrokes: 6,
  },
  叢: {
    pronunciation: '총',
    meaning: '모일',
    strokeCount: 18,
    radical: '又',
    radicalName: '又부',
    radicalStrokes: 2,
  },
  趨: {
    pronunciation: '추',
    meaning: '달릴',
    strokeCount: 17,
    radical: '走',
    radicalName: '走부',
    radicalStrokes: 7,
  },
  蹴: {
    pronunciation: '축',
    meaning: '찰',
    strokeCount: 19,
    radical: '足',
    radicalName: '足부',
    radicalStrokes: 7,
  },
  炊: {
    pronunciation: '취',
    meaning: '불을',
    strokeCount: 8,
    radical: '火',
    radicalName: '火부',
    radicalStrokes: 4,
  },
  勅: {
    pronunciation: '칙',
    meaning: '칙령',
    strokeCount: 9,
    radical: '力',
    radicalName: '力부',
    radicalStrokes: 2,
  },
  鍼: {
    pronunciation: '침',
    meaning: '바늘',
    strokeCount: 17,
    radical: '金',
    radicalName: '金부',
    radicalStrokes: 8,
  },
  灸: {
    pronunciation: '구',
    meaning: '뜸',
    strokeCount: 7,
    radical: '火',
    radicalName: '火부',
    radicalStrokes: 4,
  },
  琢: {
    pronunciation: '탁',
    meaning: '다듬을',
    strokeCount: 12,
    radical: '玉',
    radicalName: '玉부',
    radicalStrokes: 5,
  },
  耽: {
    pronunciation: '탐',
    meaning: '즐길',
    strokeCount: 10,
    radical: '耳',
    radicalName: '耳부',
    radicalStrokes: 6,
  },
  溺: {
    pronunciation: '닉',
    meaning: '빠질',
    strokeCount: 13,
    radical: '水',
    radicalName: '水부',
    radicalStrokes: 4,
  },
  胎: {
    pronunciation: '태',
    meaning: '태아',
    strokeCount: 9,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  颱: {
    pronunciation: '태',
    meaning: '태풍',
    strokeCount: 14,
    radical: '風',
    radicalName: '風부',
    radicalStrokes: 9,
  },
  兎: {
    pronunciation: '토',
    meaning: '토끼',
    strokeCount: 7,
    radical: '儿',
    radicalName: '儿부',
    radicalStrokes: 2,
  },
  鼈: {
    pronunciation: '별',
    meaning: '자라',
    strokeCount: 25,
    radical: '黽',
    radicalName: '黽부',
    radicalStrokes: 13,
  },
  堆: {
    pronunciation: '퇴',
    meaning: '쌓일',
    strokeCount: 11,
    radical: '土',
    radicalName: '土부',
    radicalStrokes: 3,
  },
  握: {
    pronunciation: '악',
    meaning: '쥘',
    strokeCount: 12,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  覇: {
    pronunciation: '패',
    meaning: '패권',
    strokeCount: 19,
    radical: '襾',
    radicalName: '襾부',
    radicalStrokes: 6,
  },
  輯: {
    pronunciation: '집',
    meaning: '모을',
    strokeCount: 16,
    radical: '車',
    radicalName: '車부',
    radicalStrokes: 7,
  },
  帛: {
    pronunciation: '백',
    meaning: '비단',
    strokeCount: 8,
    radical: '巾',
    radicalName: '巾부',
    radicalStrokes: 3,
  },
  抛: {
    pronunciation: '포',
    meaning: '던질',
    strokeCount: 8,
    radical: '手',
    radicalName: '手부',
    radicalStrokes: 4,
  },
  葡: {
    pronunciation: '포',
    meaning: '포도',
    strokeCount: 12,
    radical: '艸',
    radicalName: '艸부',
    radicalStrokes: 6,
  },
  萄: {
    pronunciation: '도',
    meaning: '포도',
    strokeCount: 11,
    radical: '艸',
    radicalName: '艸부',
    radicalStrokes: 6,
  },
  虜: {
    pronunciation: '로',
    meaning: '포로',
    strokeCount: 13,
    radical: '虍',
    radicalName: '虍부',
    radicalStrokes: 6,
  },
  瑕: {
    pronunciation: '하',
    meaning: '흠',
    strokeCount: 13,
    radical: '玉',
    radicalName: '玉부',
    radicalStrokes: 5,
  },
  疵: {
    pronunciation: '치',
    meaning: '흠',
    strokeCount: 11,
    radical: '疒',
    radicalName: '疒부',
    radicalStrokes: 5,
  },
  虐: {
    pronunciation: '학',
    meaning: '학대',
    strokeCount: 9,
    radical: '虍',
    radicalName: '虍부',
    radicalStrokes: 6,
  },
  魃: {
    pronunciation: '발',
    meaning: '가뭄귀신',
    strokeCount: 14,
    radical: '鬼',
    radicalName: '鬼부',
    radicalStrokes: 10,
  },
  函: {
    pronunciation: '함',
    meaning: '상자',
    strokeCount: 8,
    radical: '凵',
    radicalName: '凵부',
    radicalStrokes: 2,
  },
  亢: {
    pronunciation: '강',
    meaning: '높을',
    strokeCount: 4,
    radical: '亠',
    radicalName: '亠부',
    radicalStrokes: 2,
  },
  剖: {
    pronunciation: '부',
    meaning: '가를',
    strokeCount: 10,
    radical: '刀',
    radicalName: '刀부',
    radicalStrokes: 2,
  },
  酷: {
    pronunciation: '혹',
    meaning: '가혹할',
    strokeCount: 14,
    radical: '酉',
    radicalName: '酉부',
    radicalStrokes: 7,
  },
  魄: {
    pronunciation: '백',
    meaning: '넋',
    strokeCount: 14,
    radical: '鬼',
    radicalName: '鬼부',
    radicalStrokes: 10,
  },
  幻: {
    pronunciation: '환',
    meaning: '환상',
    strokeCount: 4,
    radical: '幺',
    radicalName: '幺부',
    radicalStrokes: 3,
  },
  闊: {
    pronunciation: '활',
    meaning: '넓을',
    strokeCount: 17,
    radical: '門',
    radicalName: '門부',
    radicalStrokes: 8,
  },
  膾: {
    pronunciation: '회',
    meaning: '회',
    strokeCount: 17,
    radical: '肉',
    radicalName: '肉부',
    radicalStrokes: 6,
  },
  炙: {
    pronunciation: '자',
    meaning: '구울',
    strokeCount: 8,
    radical: '火',
    radicalName: '火부',
    radicalStrokes: 4,
  },
  嚆: {
    pronunciation: '호',
    meaning: '울',
    strokeCount: 17,
    radical: '口',
    radicalName: '口부',
    radicalStrokes: 3,
  },
  勳: {
    pronunciation: '훈',
    meaning: '공훈',
    strokeCount: 16,
    radical: '力',
    radicalName: '力부',
    radicalStrokes: 2,
  },
  憩: {
    pronunciation: '게',
    meaning: '쉴',
    strokeCount: 16,
    radical: '心',
    radicalName: '心부',
    radicalStrokes: 4,
  },
  戱: {
    pronunciation: '희',
    meaning: '놀이',
    strokeCount: 15,
    radical: '戈',
    radicalName: '戈부',
    radicalStrokes: 4,
  },
  犧: {
    pronunciation: '희',
    meaning: '희생',
    strokeCount: 20,
    radical: '牛',
    radicalName: '牛부',
    radicalStrokes: 4,
  },
  牲: {
    pronunciation: '생',
    meaning: '희생',
    strokeCount: 9,
    radical: '牛',
    radicalName: '牛부',
    radicalStrokes: 4,
  },
};

// characterData.ts에서 누락된 한자들의 정보를 업데이트
const updateCharacterInfo = () => {
  const characterDataPath = path.join(
    __dirname,
    '../src/data/characterData.ts'
  );
  let content = fs.readFileSync(characterDataPath, 'utf8');

  // 각 한자 정보를 업데이트
  Object.entries(characterInfoMap).forEach(([char, info]) => {
    const regex = new RegExp(
      `(id: 'missing_char_\\d+',\\s*character: '${char}',\\s*pronunciation: '\\?',\\s*meaning: '정보 없음',\\s*strokeCount: 0,\\s*radical: '\\?',\\s*radicalName: '\\?부',\\s*radicalStrokes: 0,)`,
      'g'
    );

    const replacement = `id: 'missing_char_${char.charCodeAt(0)}', character: '${char}', pronunciation: '${info.pronunciation}', meaning: '${info.meaning}', strokeCount: ${info.strokeCount}, radical: '${info.radical}', radicalName: '${info.radicalName}', radicalStrokes: ${info.radicalStrokes},`;

    content = content.replace(regex, replacement);
  });

  // 백업 생성
  const backupPath = characterDataPath + '.backup2';
  fs.copyFileSync(characterDataPath, backupPath);
  console.log(`📁 백업 생성: ${backupPath}`);

  // 업데이트된 파일 저장
  fs.writeFileSync(characterDataPath, content);
  console.log(
    `✅ ${Object.keys(characterInfoMap).length}개 한자 정보 업데이트 완료`
  );
};

const main = () => {
  console.log('🔧 누락된 한자들의 실제 정보 업데이트 중...');

  try {
    updateCharacterInfo();
    console.log('🎯 한자 정보 업데이트 완료!');
    console.log(
      '📝 다음 단계: hanjaDebug.appReset() 실행하여 데이터베이스 재초기화'
    );
  } catch (error) {
    console.error('❌ 오류 발생:', error);
  }
};

main();
